# Generated by Django 3.1.7 on 2021-03-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='содержание')),
                ('photo', models.ImageField(upload_to='promo_photos', verbose_name='изображение')),
                ('active', models.BooleanField(verbose_name='действует')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='активно с')),
                ('active_till', models.DateTimeField(verbose_name='активно до')),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
            },
        ),
    ]
