# Generated by Django 3.1.7 on 2021-03-29 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_auto_20210321_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
    ]
