# Generated by Django 3.1.7 on 2021-03-29 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_auto_20210329_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
