# Generated by Django 3.1.7 on 2021-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210315_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
