# Generated by Django 3.1.7 on 2021-03-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210315_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='product_content_type',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='product_option_content_type',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='product_option_id',
        ),
    ]
