# Generated by Django 3.1.7 on 2021-03-18 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productoptionversion_productversion'),
        ('orders', '0005_auto_20210318_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='product_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='products.productversion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproductoption',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderedproductoption',
            name='product_option_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product_options', to='products.productoptionversion'),
        ),
    ]
