# Generated by Django 3.1.7 on 2021-03-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210321_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='option_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OrderedProductOption',
        ),
    ]
