# Generated by Django 3.1.7 on 2021-03-29 17:55

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('orders', 'Order')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
