# Generated by Django 3.1.7 on 2021-03-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'аксесуар',
                'verbose_name_plural': 'аксесуары',
            },
        ),
        migrations.CreateModel(
            name='Armchair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'кресло',
                'verbose_name_plural': 'кресла',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=128, verbose_name='размер')),
                ('mechanism', models.CharField(max_length=128, verbose_name='механизм')),
                ('headboard', models.CharField(max_length=128, verbose_name='форма изголовья')),
            ],
            options={
                'verbose_name': 'кровать',
                'verbose_name_plural': 'кровати',
            },
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'стул',
                'verbose_name_plural': 'стулья',
            },
        ),
        migrations.CreateModel(
            name='Kitchenware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'кухонная утварь',
                'verbose_name_plural': 'кухонная утварь',
            },
        ),
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=128, verbose_name='размер')),
                ('mechanism', models.CharField(max_length=128, verbose_name='механизм')),
                ('collection', models.CharField(blank=True, max_length=128, verbose_name='коллекция')),
                ('code', models.CharField(max_length=128, verbose_name='артикул')),
            ],
            options={
                'verbose_name': 'диван',
                'verbose_name_plural': 'диваны',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='тип')),
                ('collection', models.CharField(blank=True, max_length=128, verbose_name='коллекция')),
            ],
            options={
                'verbose_name': 'стол',
                'verbose_name_plural': 'столы',
            },
        ),
        migrations.RemoveField(
            model_name='productoptionchoice',
            name='option',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар, общие данные', 'verbose_name_plural': 'товары, общие данные'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='наименование'),
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
        migrations.DeleteModel(
            name='ProductOptionChoice',
        ),
        migrations.AddField(
            model_name='table',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='общие данные товара'),
        ),
        migrations.AddField(
            model_name='sofa',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='общие данные товара'),
        ),
        migrations.AddField(
            model_name='kitchenware',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='общие данные товара'),
        ),
        migrations.AddField(
            model_name='chair',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='общие данные товара'),
        ),
        migrations.AddField(
            model_name='bed',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='общие данные товара'),
        ),
        migrations.AddField(
            model_name='armchair',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='общие данные товара'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='общие данные товара'),
        ),
    ]
