# Generated by Django 3.1.7 on 2021-03-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0005_auto_20210313_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='product_photos', verbose_name='изображение')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'изображение товара',
                'verbose_name_plural': 'изображения товара',
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='product_videos', verbose_name='видео')),
            ],
            options={
                'verbose_name': 'видео товара',
                'verbose_name_plural': 'видео товара',
            },
        ),
        migrations.RemoveField(
            model_name='accessoryvideo',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='armchairphoto',
            name='armchair',
        ),
        migrations.RemoveField(
            model_name='armchairvideo',
            name='armchair',
        ),
        migrations.RemoveField(
            model_name='bedphoto',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='bedvideo',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='chairphoto',
            name='chair',
        ),
        migrations.RemoveField(
            model_name='chairvideo',
            name='chair',
        ),
        migrations.RemoveField(
            model_name='kitchenwarephoto',
            name='kitchenware',
        ),
        migrations.RemoveField(
            model_name='kitchenwarevideo',
            name='kitchenware',
        ),
        migrations.RemoveField(
            model_name='sofaphoto',
            name='sofa',
        ),
        migrations.RemoveField(
            model_name='sofavideo',
            name='sofa',
        ),
        migrations.RemoveField(
            model_name='tablephoto',
            name='table',
        ),
        migrations.RemoveField(
            model_name='tablevideo',
            name='table',
        ),
        migrations.DeleteModel(
            name='AccessoryPhoto',
        ),
        migrations.DeleteModel(
            name='AccessoryVideo',
        ),
        migrations.DeleteModel(
            name='ArmchairPhoto',
        ),
        migrations.DeleteModel(
            name='ArmchairVideo',
        ),
        migrations.DeleteModel(
            name='BedPhoto',
        ),
        migrations.DeleteModel(
            name='BedVideo',
        ),
        migrations.DeleteModel(
            name='ChairPhoto',
        ),
        migrations.DeleteModel(
            name='ChairVideo',
        ),
        migrations.DeleteModel(
            name='KitchenwarePhoto',
        ),
        migrations.DeleteModel(
            name='KitchenwareVideo',
        ),
        migrations.DeleteModel(
            name='SofaPhoto',
        ),
        migrations.DeleteModel(
            name='SofaVideo',
        ),
        migrations.DeleteModel(
            name='TablePhoto',
        ),
        migrations.DeleteModel(
            name='TableVideo',
        ),
    ]
