# Generated by Django 3.1.7 on 2021-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210314_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessory',
            name='product_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='артикул'),
        ),
        migrations.AddField(
            model_name='armchair',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armchair',
            name='product_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='артикул'),
        ),
        migrations.AddField(
            model_name='bed',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bed',
            name='product_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='артикул'),
        ),
        migrations.AddField(
            model_name='chair',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chair',
            name='product_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='артикул'),
        ),
        migrations.AddField(
            model_name='kitchenware',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchenware',
            name='product_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='артикул'),
        ),
        migrations.AddField(
            model_name='sofa',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sofa',
            name='product_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='артикул'),
        ),
        migrations.AddField(
            model_name='table',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='product_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='артикул'),
        ),
    ]
