# Generated by Django 3.1.7 on 2021-03-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210315_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sofa',
            name='code',
        ),
        migrations.AddField(
            model_name='sofaoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sofaoption',
            name='product_code',
            field=models.CharField(default=1, max_length=128, verbose_name='артикул'),
            preserve_default=False,
        ),
    ]
