# Generated by Django 3.1.7 on 2021-03-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210315_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofaoption',
            name='product_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='артикул'),
        ),
    ]
