# Generated by Django 3.1.7 on 2021-03-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productoptionversion_productversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptionversion',
            name='actual_to',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='actual_to',
            field=models.DateTimeField(blank=True),
        ),
    ]
