# Generated by Django 3.1.7 on 2021-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210318_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptionversion',
            name='actual_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='actual_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
