# Generated by Django 3.1.7 on 2021-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210318_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofaoption',
            name='product_code',
            field=models.CharField(max_length=128, verbose_name='артикул'),
        ),
    ]
