# Generated by Django 3.1.7 on 2021-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210321_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sofaoption',
            name='price',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='armchair',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='kitchenware',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='sofa',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='стоимость'),
        ),
    ]
