# Generated by Django 3.1.7 on 2021-03-29 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210321_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='armchair',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chair',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='kitchenware',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sofa',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
    ]
