# Generated by Django 3.1.7 on 2021-03-29 17:35

from django.db import migrations, models
import uuid

allowed_objects = [
    "sofa",
    "bed",
    "table",
    "armchair",
    "chair",
    "kitchenware",
    "accessory",
]


def gen_uuid(apps, schema_editor):
    for obj in allowed_objects:
        MyModel = apps.get_model('products', obj.capitalize())
        for row in MyModel.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210329_2035'),
    ]

    operations = [migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
                  ]
