# Generated by Django 3.1.7 on 2021-03-29 17:45
import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('products', 'SofaOption')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_sofaoption_uuid'),
    ]

    operations = [migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
                  ]
