# Generated by Django 3.1.7 on 2021-04-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210329_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='main_photo',
            field=models.ImageField(default='kek', upload_to='product_photos', verbose_name='основная фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armchair',
            name='main_photo',
            field=models.ImageField(default='kek', upload_to='product_photos', verbose_name='основная фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bed',
            name='main_photo',
            field=models.ImageField(default='kek', upload_to='product_photos', verbose_name='основная фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chair',
            name='main_photo',
            field=models.ImageField(default='kek', upload_to='product_photos', verbose_name='основная фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchenware',
            name='main_photo',
            field=models.ImageField(default='kek', upload_to='product_photos', verbose_name='основная фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sofa',
            name='main_photo',
            field=models.ImageField(default='kek', upload_to='product_photos', verbose_name='основная фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='main_photo',
            field=models.ImageField(default='kek', upload_to='product_photos', verbose_name='основная фотография'),
            preserve_default=False,
        ),
    ]
