# Generated by Django 3.1.7 on 2021-03-31 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='наименование')),
                ('color', models.CharField(max_length=64, verbose_name='цвет')),
                ('square', models.CharField(max_length=64, verbose_name='площадь')),
                ('room_type', models.CharField(max_length=64, verbose_name='тип комнаты')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'изображение интерьера',
                'verbose_name_plural': 'изображения интерьера',
            },
        ),
        migrations.CreateModel(
            name='InteriorPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='interior_photos', verbose_name='изображение')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ready_interiors.interior', verbose_name='интерьер')),
            ],
            options={
                'verbose_name': 'изображение интерьера',
                'verbose_name_plural': 'изображения интерьера',
            },
        ),
    ]
