# Generated by Django 3.1.7 on 2021-03-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_interiors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interior',
            options={'verbose_name': 'готовый интерьер', 'verbose_name_plural': 'готовые интерьеры'},
        ),
        migrations.AlterField(
            model_name='interior',
            name='color',
            field=models.CharField(choices=[('красный', 'красный'), ('зелёный', 'зелёный'), ('синий', 'синий'), ('оранжевый', 'оранжевый')], max_length=64, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='interior',
            name='room_type',
            field=models.CharField(choices=[('детская', 'детская'), ('кухня', 'кухня')], max_length=64, verbose_name='тип комнаты'),
        ),
        migrations.AlterField(
            model_name='interior',
            name='square',
            field=models.CharField(choices=[('до 30м2', 'до 30м2'), ('до 50м2', 'до 50м2')], max_length=64, verbose_name='площадь'),
        ),
    ]
